### ISSUE TITLE
Error when cleaning directory in workflow with action-clean v1.1.1

### ISSUE THREAD

**Issue by lkreimann** [AutoModality/action-clean#6]
Hello :wave: 
We have a mysterious error when cleaning the directory in our workflows with this action (using version 1.1.1): 
![grafik](https://user-images.githubusercontent.com/22977266/130599128-4ad502c0-7893-4e79-9d35-fb17ff441985.png)

We're using the action in this way: 
```yaml
    steps:
      - name: Clean Directory
        uses: AutoModality/action-clean@v1.1.1
```
(Can't link to our workflow bc we only have private repos)

Can someone help with that? I'm not really sure where this error comes from. 

Have a good day :v:
